# Generated by Django 3.0.5 on 2020-11-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201114_2019'),
        ('users', '0002_auto_20201119_1812'),
    ]

    operations = [
    ]
