# Generated by Django 3.0.5 on 2020-11-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20201120_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code_active',
            field=models.BooleanField(default=False, help_text='If True you can use this code to get the token'),
        ),
    ]
